server:
  port: 9296
  
spring:
  profiles:
    active: git
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vatsalya-singhi/spring-boot-config-server
          default-label: master
          skipSslValidation: true
          clone-on-start: true
