management:
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreaker.enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    url: >-
      jdbc:mysql://avnadmin:AVNS_LIPzdDuNm-wC4OZbeQt@mysql-29cd077f-spring-boot-starter.e.aivencloud.com:26367/defaultdb
    password: AVNS_LIPzdDuNm-wC4OZbeQt
  application:
    name: DEPARTMENT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
  ziplin:
    base-url: http://localhost:9411/
server:
  port: 9001
