spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    url: >-
      jdbc:mysql://avnadmin:AVNS_LIPzdDuNm-wC4OZbeQt@mysql-29cd077f-spring-boot-starter.e.aivencloud.com:26367/defaultdb
    password: AVNS_LIPzdDuNm-wC4OZbeQt
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
  ziplin:
    base-url: http://localhost:9411/

server:
  port: 9002
